name: acl-cross-platform-build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - docs/**
      - '**/*.md'

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build linux x86 SSE2
        run: |
          mkdir build_linux_sse2
          cd build_linux_sse2
          cmake .. -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DCMAKE_CXX_COMPILER="clang-12"
          cd ..
          cmake --build build_linux_sse2
          cd build_linux_sse2
          mv libAclUnity.so AclUnity.so
          cd ..
      - name: Build linux x86 AVX
        run: |
          mkdir build_linux_avx
          cd build_linux_avx
          cmake .. -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DACLUNITY_IS_AVX:BOOL="True" -DCMAKE_CXX_COMPILER="clang-12"
          cd ..
          cmake --build build_linux_avx
          cd build_linux_avx
          mv libAclUnity_AVX.so AclUnity_AVX.so
          cd ..
      - name: Upload linux artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifacts
          path: |
            ./build*/**/*.so*
            ./build*/**/*.s
            
  windows:
    runs-on: windows-2019
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build windows x86 SSE2
        run: |
          mkdir build_windows_sse2
          cd build_windows_sse2
          cmake .. -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo"
          cd ..
          cmake --build build_windows_sse2 --config RelWithDebInfo
      - name: Build linux x86 AVX
        run: |
          mkdir build_windows_avx
          cd build_windows_avx
          cmake .. -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DACLUNITY_IS_AVX:BOOL="True"
          cd ..
          cmake --build build_windows_avx --config RelWithDebInfo
      - name: Upload windows artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-artifacts
          path: |
            ./build*/**/*.dll
            ./build*/**/*.pdb
            ./build*/**/*.asm