name: acl-cross-platform-build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - docs/**
      - '**/*.md'

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build linux x86 SSE2
        run: |
          mkdir build_linux_sse2
          cd build_linux_sse2
          cmake .. -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DCMAKE_CXX_COMPILER="clang-12"
          cd ..
          cmake --build build_linux_sse2
          cd build_linux_sse2
          mv libAclUnity.so AclUnity.so
          objcopy --only-keep-debug AclUnity.so AclUnity.so.debug
          strip --strip-debug AclUnity.so
          objcopy --add-gnu-debuglink=AclUnity.so.debug AclUnity.so
          cd ..
      - name: Build linux x86 AVX
        run: |
          mkdir build_linux_avx
          cd build_linux_avx
          cmake .. -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DACLUNITY_IS_AVX:BOOL="True" -DCMAKE_CXX_COMPILER="clang-12"
          cd ..
          cmake --build build_linux_avx
          cd build_linux_avx
          mv libAclUnity_AVX.so AclUnity_AVX.so
          objcopy --only-keep-debug AclUnity_AVX.so AclUnity_AVX.so.debug
          strip --strip-debug AclUnity_AVX.so
          objcopy --add-gnu-debuglink=AclUnity_AVX.so.debug AclUnity_AVX.so
          cd ..
      - name: Build Android
        run: |
          cmake -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DCMAKE_TOOLCHAIN_FILE="cmake/android-toolchain.cmake" -B "build_android"
          cmake --build build_android
      - name: Upload linux artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifacts
          path: |
            ./build*/**/*.so*
            ./build*/**/*.s
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
            
  windows:
    runs-on: windows-2019
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build windows x86 SSE2
        run: |
          mkdir build_windows_sse2
          cd build_windows_sse2
          cmake .. -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo"
          cd ..
          cmake --build build_windows_sse2 --config RelWithDebInfo
      - name: Build windows x86 AVX
        run: |
          mkdir build_windows_avx
          cd build_windows_avx
          cmake .. -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DACLUNITY_IS_AVX:BOOL="True"
          cd ..
          cmake --build build_windows_avx --config RelWithDebInfo
      - name: Upload windows artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-artifacts
          path: |
            ./build*/**/*.dll
            ./build*/**/*.pdb
            ./build*/**/*.asm
            
  osx:
    runs-on: macos-12
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build osx arm
        run: |
          mkdir build_osx_arm
          cd build_osx_arm
          cmake .. -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DCMAKE_OSX_ARCHITECTURES:STRING="arm64"
          cd ..
          cmake --build build_osx_arm
          cd build_osx_arm
          mv libAclUnity.dylib AclUnity.dylib
          cd ..
      - name: Build osx x86 SSE2
        run: |
          mkdir build_osx_x86_sse2
          cd build_osx_x86_sse2
          cmake .. -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DCMAKE_OSX_ARCHITECTURES:STRING="x86_64"
          cd ..
          cmake --build build_osx_x86_sse2
          cd build_osx_x86_sse2
          mv libAclUnity.dylib AclUnity.dylib
          cd ..
      - name: Build osx x86 AVX
        run: |
          mkdir build_osx_x86_avx
          cd build_osx_x86_avx
          cmake .. -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DCMAKE_OSX_ARCHITECTURES:STRING="x86_64" -DACLUNITY_IS_AVX:BOOL="True"
          cd ..
          cmake --build build_osx_x86_avx
          cd build_osx_x86_avx
          mv libAclUnity_AVX.dylib AclUnity_AVX.dylib
          cd ..
      - name: Upload osx artifacts
        uses: actions/upload-artifact@v3
        with:
          name: osx-artifacts
          path: |
            ./build*/**/*.dylib
            ./build*/**/*.s